// Generated from the recorded voice lines. Do not edit by hand.

/// Bibi's recorded voice: normalised line text to clip file in assets/voice.
const voiceClips = <String, String>{
  "zero": 'v000',
  "one": 'v001',
  "two": 'v002',
  "three": 'v003',
  "four": 'v004',
  "five": 'v005',
  "six": 'v006',
  "seven": 'v007',
  "eight": 'v008',
  "nine": 'v009',
  "ten": 'v010',
  "my tummy is rumbling": 'v011',
  "nom nom nom": 'v012',
  "whoa that's too many for my little tummy": 'v013',
  "hmm i'm still hungry i need a few more": 'v014',
  "my bowl is empty tap the fruit to fill it up": 'v015',
  "can you give me one apple please": 'v016',
  "can you give me one strawberry please": 'v017',
  "can you give me one banana please": 'v018',
  "can you give me one blueberry please": 'v019',
  "can you give me one cookie please": 'v020',
  "can you give me one orange please": 'v021',
  "can you give me two apples please": 'v022',
  "can you give me two strawberries please": 'v023',
  "can you give me two bananas please": 'v024',
  "can you give me two blueberries please": 'v025',
  "can you give me two cookies please": 'v026',
  "can you give me two oranges please": 'v027',
  "can you give me three apples please": 'v028',
  "can you give me three strawberries please": 'v029',
  "can you give me three bananas please": 'v030',
  "can you give me three blueberries please": 'v031',
  "can you give me three cookies please": 'v032',
  "can you give me three oranges please": 'v033',
  "can you give me four apples please": 'v034',
  "can you give me four strawberries please": 'v035',
  "can you give me four bananas please": 'v036',
  "can you give me four blueberries please": 'v037',
  "can you give me four cookies please": 'v038',
  "can you give me four oranges please": 'v039',
  "can you give me five apples please": 'v040',
  "can you give me five strawberries please": 'v041',
  "can you give me five bananas please": 'v042',
  "can you give me five blueberries please": 'v043',
  "can you give me five cookies please": 'v044',
  "can you give me five oranges please": 'v045',
  "can you give me six apples please": 'v046',
  "can you give me six strawberries please": 'v047',
  "can you give me six bananas please": 'v048',
  "can you give me six blueberries please": 'v049',
  "can you give me six cookies please": 'v050',
  "can you give me six oranges please": 'v051',
  "can you give me seven apples please": 'v052',
  "can you give me seven strawberries please": 'v053',
  "can you give me seven bananas please": 'v054',
  "can you give me seven blueberries please": 'v055',
  "can you give me seven cookies please": 'v056',
  "can you give me seven oranges please": 'v057',
  "can you give me eight apples please": 'v058',
  "can you give me eight strawberries please": 'v059',
  "can you give me eight bananas please": 'v060',
  "can you give me eight blueberries please": 'v061',
  "can you give me eight cookies please": 'v062',
  "can you give me eight oranges please": 'v063',
  "can you give me nine apples please": 'v064',
  "can you give me nine strawberries please": 'v065',
  "can you give me nine bananas please": 'v066',
  "can you give me nine blueberries please": 'v067',
  "can you give me nine cookies please": 'v068',
  "can you give me nine oranges please": 'v069',
  "can you give me ten apples please": 'v070',
  "can you give me ten strawberries please": 'v071',
  "can you give me ten bananas please": 'v072',
  "can you give me ten blueberries please": 'v073',
  "can you give me ten cookies please": 'v074',
  "can you give me ten oranges please": 'v075',
  "yes brilliant": 'v076',
  "you got it": 'v077',
  "woohoo well done": 'v078',
  "super clever": 'v079',
  "yay that's right": 'v080',
  "this is a it says ah": 'v081',
  "which picture starts with ah": 'v082',
  "ah ah ant": 'v083',
  "that's an ant": 'v084',
  "i think it starts with a am i right": 'v085',
  "it starts with a": 'v086',
  "this is b it says buh": 'v087',
  "which picture starts with buh": 'v088',
  "buh buh bear": 'v089',
  "that's a bear": 'v090',
  "i think it starts with b am i right": 'v091',
  "it starts with b": 'v092',
  "this is c it says kuh": 'v093',
  "which picture starts with kuh": 'v094',
  "kuh kuh cat": 'v095',
  "that's a cat": 'v096',
  "i think it starts with c am i right": 'v097',
  "it starts with c": 'v098',
  "this is d it says duh": 'v099',
  "which picture starts with duh": 'v100',
  "duh duh dog": 'v101',
  "that's a dog": 'v102',
  "i think it starts with d am i right": 'v103',
  "it starts with d": 'v104',
  "this is e it says eh": 'v105',
  "which picture starts with eh": 'v106',
  "eh eh egg": 'v107',
  "that's an egg": 'v108',
  "i think it starts with e am i right": 'v109',
  "it starts with e": 'v110',
  "this is f it says ffff": 'v111',
  "which picture starts with ffff": 'v112',
  "ffff ffff fish": 'v113',
  "that's a fish": 'v114',
  "i think it starts with f am i right": 'v115',
  "it starts with f": 'v116',
  "this is g it says guh": 'v117',
  "which picture starts with guh": 'v118',
  "guh guh gorilla": 'v119',
  "that's a gorilla": 'v120',
  "i think it starts with g am i right": 'v121',
  "it starts with g": 'v122',
  "this is h it says huh": 'v123',
  "which picture starts with huh": 'v124',
  "huh huh hat": 'v125',
  "that's a hat": 'v126',
  "i think it starts with h am i right": 'v127',
  "it starts with h": 'v128',
  "this is l it says llll": 'v129',
  "which picture starts with llll": 'v130',
  "llll llll lion": 'v131',
  "that's a lion": 'v132',
  "i think it starts with l am i right": 'v133',
  "it starts with l": 'v134',
  "this is m it says mmmm": 'v135',
  "which picture starts with mmmm": 'v136',
  "mmmm mmmm monkey": 'v137',
  "that's a monkey": 'v138',
  "i think it starts with m am i right": 'v139',
  "it starts with m": 'v140',
  "this is n it says nnnn": 'v141',
  "which picture starts with nnnn": 'v142',
  "nnnn nnnn nest": 'v143',
  "that's a nest": 'v144',
  "i think it starts with n am i right": 'v145',
  "it starts with n": 'v146',
  "this is o it says oh": 'v147',
  "which picture starts with oh": 'v148',
  "oh oh octopus": 'v149',
  "that's an octopus": 'v150',
  "i think it starts with o am i right": 'v151',
  "it starts with o": 'v152',
  "this is p it says puh": 'v153',
  "which picture starts with puh": 'v154',
  "puh puh pig": 'v155',
  "that's a pig": 'v156',
  "i think it starts with p am i right": 'v157',
  "it starts with p": 'v158',
  "this is r it says rrrr": 'v159',
  "which picture starts with rrrr": 'v160',
  "rrrr rrrr rainbow": 'v161',
  "that's a rainbow": 'v162',
  "i think it starts with r am i right": 'v163',
  "it starts with r": 'v164',
  "this is s it says ssss": 'v165',
  "which picture starts with ssss": 'v166',
  "ssss ssss sun": 'v167',
  "that's the sun": 'v168',
  "i think it starts with s am i right": 'v169',
  "it starts with s": 'v170',
  "this is t it says tuh": 'v171',
  "which picture starts with tuh": 'v172',
  "tuh tuh turtle": 'v173',
  "that's a turtle": 'v174',
  "i think it starts with t am i right": 'v175',
  "it starts with t": 'v176',
  "this is z it says zzzz": 'v177',
  "which picture starts with zzzz": 'v178',
  "zzzz zzzz zebra": 'v179',
  "that's a zebra": 'v180',
  "i think it starts with z am i right": 'v181',
  "it starts with z": 'v182',
  "let's build a house": 'v183',
  "look we built a whole house together": 'v184',
  "find the square for the walls": 'v185',
  "now find the triangle for the roof": 'v186',
  "now find the rectangle for the door": 'v187',
  "now find the circle for the sun": 'v188',
  "now find the star for the sky": 'v189',
  "a square": 'v190',
  "that's a square": 'v191',
  "can you find the square": 'v192',
  "a triangle": 'v193',
  "that's a triangle": 'v194',
  "can you find the triangle": 'v195',
  "a rectangle": 'v196',
  "that's a rectangle": 'v197',
  "can you find the rectangle": 'v198',
  "a circle": 'v199',
  "that's a circle": 'v200',
  "can you find the circle": 'v201',
  "a star": 'v202',
  "that's a star": 'v203',
  "can you find the star": 'v204',
  "a heart": 'v205',
  "that's a heart": 'v206',
  "can you find the heart": 'v207',
  "a diamond": 'v208',
  "that's a diamond": 'v209',
  "can you find the diamond": 'v210',
  "an oval": 'v211',
  "that's an oval": 'v212',
  "can you find the oval": 'v213',
  "balloon": 'v214',
  "cake": 'v215',
  "present": 'v216',
  "star": 'v217',
  "strawberry": 'v218',
  "cupcake": 'v219',
  "popper": 'v220',
  "lolly": 'v221',
  "party time": 'v222',
  "what comes next": 'v223',
  "let's party": 'v224',
  "hmm let's sing the pattern together": 'v225',
  "i'm learning to count let me try": 'v226',
  "let me count these": 'v227',
  "yippee i got one right thank you for checking teacher": 'v228',
  "hmm i think i was counting my toes": 'v229',
  "oopsie my brain did a wobble": 'v230',
  "silly me my leaf was in my eyes": 'v231',
  "oh no i was thinking about cake again": 'v232',
  "can you teach me how many are there really": 'v233',
  "can you teach me which letter does it start with": 'v234',
  "hmm let's count together": 'v235',
  "ohhh now i know you are the best teacher": 'v236',
  "hmm shall we count them together tap each one": 'v237',
  "listen carefully and try again": 'v238',
  "i think there is one am i right": 'v239',
  "there is one": 'v240',
  "i think there are two am i right": 'v241',
  "there are two": 'v242',
  "i think there are three am i right": 'v243',
  "there are three": 'v244',
  "i think there are four am i right": 'v245',
  "there are four": 'v246',
  "i think there are five am i right": 'v247',
  "there are five": 'v248',
  "i think there are six am i right": 'v249',
  "there are six": 'v250',
  "i think there are seven am i right": 'v251',
  "there are seven": 'v252',
  "i think there are eight am i right": 'v253',
  "there are eight": 'v254',
  "i think there are nine am i right": 'v255',
  "there are nine": 'v256',
  "i think there are ten am i right": 'v257',
  "there are ten": 'v258',
  "good morning": 'v259',
  "hello": 'v260',
  "good evening": 'v261',
  "i missed you": 'v262',
  "what shall we do next": 'v263',
  "i had a dream about you": 'v264',
  "we were flying on a giant banana": 'v265',
  "we had a picnic on the moon and the cheese was yummy": 'v266',
  "you and me were swimming with a friendly whale": 'v267',
  "we built a castle out of jelly and it wobbled": 'v268',
  "we found a rainbow slide and went whoosh": 'v269',
  "how are you feeling today": 'v270',
  "yay happy is my favourite let's have fun": 'v271',
  "aww here's a big squishy hug i'm right here with you": 'v272',
  "me too a little bit let's take it nice and slow": 'v273',
  "that's okay let's take a big dragon breath together in and out better":
      'v274',
  "hee hee that tickles": 'v275',
  "boop you booped me": 'v276',
  "i love playing with you": 'v277',
  "did you know i grow when you learn": 'v278',
  "my leaf is doing a happy dance": 'v279',
  "let's learn something amazing": 'v280',
  "look at my stars that's from all our counting": 'v281',
  "i love my book hat letters make me so clever": 'v282',
  "look at my flower i'm a superstar now": 'v283',
  "surprise i found a shiny star in my leaf it's for you": 'v284',
  "feeding time": 'v285',
  "letter garden": 'v286',
  "shape builder": 'v287',
  "pattern party": 'v288',
  "teach me": 'v289',
  "your sticker album": 'v290',
  "your letterbox": 'v291',
  "your letterbox something is waiting inside": 'v292',
  "wow i just grew bigger thank you for teaching me": 'v293',
  "you did it you are a superstar": 'v294',
  "wow my brain feels so much bigger now": 'v295',
  "hooray you are the best teacher in the whole world": 'v296',
  "amazing i'm growing because of you": 'v297',
  "and look a new sticker for your album": 'v298',
  "play a game to win your very first sticker": 'v299',
  "wow look at all your stickers": 'v300',
  "ooh shiny": 'v301',
  "i love that one": 'v302',
  "so cool": 'v303',
  "wiggle wiggle": 'v304',
  "look a magic egg tap it to wake it up": 'v305',
  "ooh it moved": 'v306',
  "keep going": 'v307',
  "i can hear something inside": 'v308',
  "one more big tap": 'v309',
  "hello i'm your very own creature what should my name be": 'v310',
  "bibi i love it i'm bibi": 'v311',
  "pip i love it i'm pip": 'v312',
  "mochi i love it i'm mochi": 'v313',
  "sunny i love it i'm sunny": 'v314',
  "bean i love it i'm bean": 'v315',
  "coco i love it i'm coco": 'v316',
  "you got a message from mummy would you like to hear what mummy has to say":
      'v317',
  "here is mummy": 'v318',
  "would you like to send mummy a big hug back": 'v319',
  "whoosh your hug is flying to mummy": 'v320',
  "mummy would love a hug back shall we send one": 'v321',
  "mummy left you a special bedtime message": 'v322',
  "you got a message from daddy would you like to hear what daddy has to say":
      'v323',
  "here is daddy": 'v324',
  "would you like to send daddy a big hug back": 'v325',
  "whoosh your hug is flying to daddy": 'v326',
  "daddy would love a hug back shall we send one": 'v327',
  "daddy left you a special bedtime message": 'v328',
  "you got a message from grandma would you like to hear what grandma has to say":
      'v329',
  "here is grandma": 'v330',
  "would you like to send grandma a big hug back": 'v331',
  "whoosh your hug is flying to grandma": 'v332',
  "grandma would love a hug back shall we send one": 'v333',
  "grandma left you a special bedtime message": 'v334',
  "you got a message from grandad would you like to hear what grandad has to say":
      'v335',
  "here is grandad": 'v336',
  "would you like to send grandad a big hug back": 'v337',
  "whoosh your hug is flying to grandad": 'v338',
  "grandad would love a hug back shall we send one": 'v339',
  "grandad left you a special bedtime message": 'v340',
  "you got a message from nana would you like to hear what nana has to say":
      'v341',
  "here is nana": 'v342',
  "would you like to send nana a big hug back": 'v343',
  "whoosh your hug is flying to nana": 'v344',
  "nana would love a hug back shall we send one": 'v345',
  "nana left you a special bedtime message": 'v346',
  "you got a message from auntie would you like to hear what auntie has to say":
      'v347',
  "here is auntie": 'v348',
  "would you like to send auntie a big hug back": 'v349',
  "whoosh your hug is flying to auntie": 'v350',
  "auntie would love a hug back shall we send one": 'v351',
  "auntie left you a special bedtime message": 'v352',
  "you got a message from uncle would you like to hear what uncle has to say":
      'v353',
  "here is uncle": 'v354',
  "would you like to send uncle a big hug back": 'v355',
  "whoosh your hug is flying to uncle": 'v356',
  "uncle would love a hug back shall we send one": 'v357',
  "uncle left you a special bedtime message": 'v358',
  "okay i'll keep it safe in your letterbox": 'v359',
  "wasn't that lovely": 'v360',
  "maybe another time": 'v361',
  "psst": 'v362',
  "no letters yet when someone who loves you sends one i will bring it straight to you":
      'v363',
  "you got a message": 'v364',
  "would you like to hear it": 'v365',
  "would you like to send a big hug back": 'v366',
  "whoosh your hug is on its way": 'v367',
  "yaaawn i'm getting sooo sleepy": 'v368',
  "before i sleep": 'v369',
  "night night": 'v370',
  "thank you for playing with me see you tomorrow": 'v371',
  "shhh i'm sleeping see you tomorrow": 'v372',
  "shhh i'm dreaming about you": 'v373',
  "i'm awake let's play a little more": 'v374',
};
