// Generated from the recorded voice lines. Do not edit by hand.

/// Recorded voices (Bibi and friends): normalised line text to clip file in assets/voice.
const voiceClips = <String, String>{
  "zero": 'b000',
  "one": 'b001',
  "two": 'b002',
  "three": 'b003',
  "four": 'b004',
  "five": 'b005',
  "six": 'b006',
  "seven": 'b007',
  "eight": 'b008',
  "nine": 'b009',
  "ten": 'b010',
  "my tummy is rumbling": 'b011',
  "nom nom nom": 'b012',
  "whoa that's too many for my little tummy": 'b013',
  "hmm i'm still hungry i need a few more": 'b014',
  "my bowl is empty tap the fruit to fill it up": 'b015',
  "can you give me one apple please": 'b016',
  "can you give me one strawberry please": 'b017',
  "can you give me one banana please": 'b018',
  "can you give me one blueberry please": 'b019',
  "can you give me one cookie please": 'b020',
  "can you give me one orange please": 'b021',
  "can you give me two apples please": 'b022',
  "can you give me two strawberries please": 'b023',
  "can you give me two bananas please": 'b024',
  "can you give me two blueberries please": 'b025',
  "can you give me two cookies please": 'b026',
  "can you give me two oranges please": 'b027',
  "can you give me three apples please": 'b028',
  "can you give me three strawberries please": 'b029',
  "can you give me three bananas please": 'b030',
  "can you give me three blueberries please": 'b031',
  "can you give me three cookies please": 'b032',
  "can you give me three oranges please": 'b033',
  "can you give me four apples please": 'b034',
  "can you give me four strawberries please": 'b035',
  "can you give me four bananas please": 'b036',
  "can you give me four blueberries please": 'b037',
  "can you give me four cookies please": 'b038',
  "can you give me four oranges please": 'b039',
  "can you give me five apples please": 'b040',
  "can you give me five strawberries please": 'b041',
  "can you give me five bananas please": 'b042',
  "can you give me five blueberries please": 'b043',
  "can you give me five cookies please": 'b044',
  "can you give me five oranges please": 'b045',
  "can you give me six apples please": 'b046',
  "can you give me six strawberries please": 'b047',
  "can you give me six bananas please": 'b048',
  "can you give me six blueberries please": 'b049',
  "can you give me six cookies please": 'b050',
  "can you give me six oranges please": 'b051',
  "can you give me seven apples please": 'b052',
  "can you give me seven strawberries please": 'b053',
  "can you give me seven bananas please": 'b054',
  "can you give me seven blueberries please": 'b055',
  "can you give me seven cookies please": 'b056',
  "can you give me seven oranges please": 'b057',
  "can you give me eight apples please": 'b058',
  "can you give me eight strawberries please": 'b059',
  "can you give me eight bananas please": 'b060',
  "can you give me eight blueberries please": 'b061',
  "can you give me eight cookies please": 'b062',
  "can you give me eight oranges please": 'b063',
  "can you give me nine apples please": 'b064',
  "can you give me nine strawberries please": 'b065',
  "can you give me nine bananas please": 'b066',
  "can you give me nine blueberries please": 'b067',
  "can you give me nine cookies please": 'b068',
  "can you give me nine oranges please": 'b069',
  "can you give me ten apples please": 'b070',
  "can you give me ten strawberries please": 'b071',
  "can you give me ten bananas please": 'b072',
  "can you give me ten blueberries please": 'b073',
  "can you give me ten cookies please": 'b074',
  "can you give me ten oranges please": 'b075',
  "yes brilliant": 'b076',
  "you got it": 'b077',
  "woohoo well done": 'b078',
  "super clever": 'b079',
  "yay that's right": 'b080',
  "this is a it says ah": 'b081',
  "pop the bubble that starts with ah": 'b082',
  "ah ah ant": 'b083',
  "that's an ant": 'b084',
  "i think it starts with a am i right": 'b085',
  "it starts with a": 'b086',
  "this is b it says buh": 'b087',
  "pop the bubble that starts with buh": 'b088',
  "buh buh bear": 'b089',
  "that's a bear": 'b090',
  "i think it starts with b am i right": 'b091',
  "it starts with b": 'b092',
  "this is c it says kuh": 'b093',
  "pop the bubble that starts with kuh": 'b094',
  "kuh kuh cat": 'b095',
  "that's a cat": 'b096',
  "i think it starts with c am i right": 'b097',
  "it starts with c": 'b098',
  "this is d it says duh": 'b099',
  "pop the bubble that starts with duh": 'b100',
  "duh duh dog": 'b101',
  "that's a dog": 'b102',
  "i think it starts with d am i right": 'b103',
  "it starts with d": 'b104',
  "this is e it says eh": 'b105',
  "pop the bubble that starts with eh": 'b106',
  "eh eh egg": 'b107',
  "that's an egg": 'b108',
  "i think it starts with e am i right": 'b109',
  "it starts with e": 'b110',
  "this is f it says ffff": 'b111',
  "pop the bubble that starts with ffff": 'b112',
  "ffff ffff fish": 'b113',
  "that's a fish": 'b114',
  "i think it starts with f am i right": 'b115',
  "it starts with f": 'b116',
  "this is g it says guh": 'b117',
  "pop the bubble that starts with guh": 'b118',
  "guh guh gorilla": 'b119',
  "that's a gorilla": 'b120',
  "i think it starts with g am i right": 'b121',
  "it starts with g": 'b122',
  "this is h it says huh": 'b123',
  "pop the bubble that starts with huh": 'b124',
  "huh huh hat": 'b125',
  "that's a hat": 'b126',
  "i think it starts with h am i right": 'b127',
  "it starts with h": 'b128',
  "this is l it says llll": 'b129',
  "pop the bubble that starts with llll": 'b130',
  "llll llll lion": 'b131',
  "that's a lion": 'b132',
  "i think it starts with l am i right": 'b133',
  "it starts with l": 'b134',
  "this is m it says mmmm": 'b135',
  "pop the bubble that starts with mmmm": 'b136',
  "mmmm mmmm monkey": 'b137',
  "that's a monkey": 'b138',
  "i think it starts with m am i right": 'b139',
  "it starts with m": 'b140',
  "this is n it says nnnn": 'b141',
  "pop the bubble that starts with nnnn": 'b142',
  "nnnn nnnn nest": 'b143',
  "that's a nest": 'b144',
  "i think it starts with n am i right": 'b145',
  "it starts with n": 'b146',
  "this is o it says oh": 'b147',
  "pop the bubble that starts with oh": 'b148',
  "oh oh octopus": 'b149',
  "that's an octopus": 'b150',
  "i think it starts with o am i right": 'b151',
  "it starts with o": 'b152',
  "this is p it says puh": 'b153',
  "pop the bubble that starts with puh": 'b154',
  "puh puh pig": 'b155',
  "that's a pig": 'b156',
  "i think it starts with p am i right": 'b157',
  "it starts with p": 'b158',
  "this is r it says rrrr": 'b159',
  "pop the bubble that starts with rrrr": 'b160',
  "rrrr rrrr rainbow": 'b161',
  "that's a rainbow": 'b162',
  "i think it starts with r am i right": 'b163',
  "it starts with r": 'b164',
  "this is s it says ssss": 'b165',
  "pop the bubble that starts with ssss": 'b166',
  "ssss ssss sun": 'b167',
  "that's the sun": 'b168',
  "i think it starts with s am i right": 'b169',
  "it starts with s": 'b170',
  "this is t it says tuh": 'b171',
  "pop the bubble that starts with tuh": 'b172',
  "tuh tuh turtle": 'b173',
  "that's a turtle": 'b174',
  "i think it starts with t am i right": 'b175',
  "it starts with t": 'b176',
  "this is z it says zzzz": 'b177',
  "pop the bubble that starts with zzzz": 'b178',
  "zzzz zzzz zebra": 'b179',
  "that's a zebra": 'b180',
  "i think it starts with z am i right": 'b181',
  "it starts with z": 'b182',
  "let's build a house": 'b183',
  "look we built a whole house together": 'b184',
  "find the square for the walls": 'b185',
  "now find the triangle for the roof": 'b186',
  "now find the rectangle for the door": 'b187',
  "now find the circle for the sun": 'b188',
  "now find the star for the sky": 'b189',
  "a square": 'b190',
  "that's a square": 'b191',
  "can you find the square": 'b192',
  "a triangle": 'b193',
  "that's a triangle": 'b194',
  "can you find the triangle": 'b195',
  "a rectangle": 'b196',
  "that's a rectangle": 'b197',
  "can you find the rectangle": 'b198',
  "a circle": 'b199',
  "that's a circle": 'b200',
  "can you find the circle": 'b201',
  "a star": 'b202',
  "that's a star": 'b203',
  "can you find the star": 'b204',
  "a heart": 'b205',
  "that's a heart": 'b206',
  "can you find the heart": 'b207',
  "a diamond": 'b208',
  "that's a diamond": 'b209',
  "can you find the diamond": 'b210',
  "an oval": 'b211',
  "that's an oval": 'b212',
  "can you find the oval": 'b213',
  "balloon": 'b214',
  "cake": 'b215',
  "present": 'b216',
  "star": 'b217',
  "strawberry": 'b218',
  "cupcake": 'b219',
  "popper": 'b220',
  "lolly": 'b221',
  "party time": 'b222',
  "what comes next": 'b223',
  "let's party": 'b224',
  "hmm let's sing the pattern together": 'b225',
  "i'm learning to count let me try": 'b226',
  "let me count these": 'b227',
  "yippee i got one right thank you for checking teacher": 'b228',
  "hmm i think i was counting my toes": 'b229',
  "oopsie my brain did a wobble": 'b230',
  "silly me my leaf was in my eyes": 'b231',
  "oh no i was thinking about cake again": 'b232',
  "can you teach me how many are there really": 'b233',
  "can you teach me which letter does it start with": 'b234',
  "hmm let's count together": 'b235',
  "ohhh now i know you are the best teacher": 'b236',
  "hmm shall we count them together tap each one": 'b237',
  "listen carefully and try again": 'b238',
  "i think there is one am i right": 'b239',
  "there is one": 'b240',
  "i think there are two am i right": 'b241',
  "there are two": 'b242',
  "i think there are three am i right": 'b243',
  "there are three": 'b244',
  "i think there are four am i right": 'b245',
  "there are four": 'b246',
  "i think there are five am i right": 'b247',
  "there are five": 'b248',
  "i think there are six am i right": 'b249',
  "there are six": 'b250',
  "i think there are seven am i right": 'b251',
  "there are seven": 'b252',
  "i think there are eight am i right": 'b253',
  "there are eight": 'b254',
  "i think there are nine am i right": 'b255',
  "there are nine": 'b256',
  "i think there are ten am i right": 'b257',
  "there are ten": 'b258',
  "good morning": 'b259',
  "hello": 'b260',
  "good evening": 'b261',
  "i missed you": 'b262',
  "what shall we do next": 'b263',
  "i had a dream about you": 'b264',
  "we were flying on a giant banana": 'b265',
  "we had a picnic on the moon and the cheese was yummy": 'b266',
  "you and me were swimming with a friendly whale": 'b267',
  "we built a castle out of jelly and it wobbled": 'b268',
  "we found a rainbow slide and went whoosh": 'b269',
  "how are you feeling today": 'b270',
  "yay happy is my favourite let's have fun": 'b271',
  "aww here's a big squishy hug i'm right here with you": 'b272',
  "me too a little bit let's take it nice and slow": 'b273',
  "that's okay let's take a big dragon breath together in and out better": 'b274',
  "hee hee that tickles": 'b275',
  "boop you booped me": 'b276',
  "i love playing with you": 'b277',
  "did you know i grow when you learn": 'b278',
  "my leaf is doing a happy dance": 'b279',
  "let's learn something amazing": 'b280',
  "look at my stars that's from all our counting": 'b281',
  "i love my book hat letters make me so clever": 'b282',
  "look at my flower i'm a superstar now": 'b283',
  "surprise i found a shiny star in my leaf it's for you": 'b284',
  "feeding time": 'b285',
  "letter garden": 'b286',
  "shape builder": 'b287',
  "pattern party": 'b288',
  "teach me": 'b289',
  "your sticker album": 'b290',
  "your letterbox": 'b291',
  "your letterbox something is waiting inside": 'b292',
  "wow i just grew bigger thank you for teaching me": 'b293',
  "you did it you are a superstar": 'b294',
  "wow my brain feels so much bigger now": 'b295',
  "hooray you are the best teacher in the whole world": 'b296',
  "amazing i'm growing because of you": 'b297',
  "and look a new sticker for your album": 'b298',
  "play a game to win your very first sticker": 'b299',
  "wow look at all your stickers": 'b300',
  "ooh shiny": 'b301',
  "i love that one": 'b302',
  "so cool": 'b303',
  "wiggle wiggle": 'b304',
  "look a magic egg tap it to wake it up": 'b305',
  "ooh it moved": 'b306',
  "keep going": 'b307',
  "i can hear something inside": 'b308',
  "one more big tap": 'b309',
  "hello i'm your very own creature what should my name be": 'b310',
  "bibi i love it i'm bibi": 'b311',
  "pip i love it i'm pip": 'b312',
  "mochi i love it i'm mochi": 'b313',
  "sunny i love it i'm sunny": 'b314',
  "bean i love it i'm bean": 'b315',
  "coco i love it i'm coco": 'b316',
  "you got a message from mummy would you like to hear what mummy has to say": 'b317',
  "here is mummy": 'b318',
  "would you like to send mummy a big hug back": 'b319',
  "whoosh your hug is flying to mummy": 'b320',
  "mummy would love a hug back shall we send one": 'b321',
  "mummy left you a special bedtime message": 'b322',
  "you got a message from daddy would you like to hear what daddy has to say": 'b323',
  "here is daddy": 'b324',
  "would you like to send daddy a big hug back": 'b325',
  "whoosh your hug is flying to daddy": 'b326',
  "daddy would love a hug back shall we send one": 'b327',
  "daddy left you a special bedtime message": 'b328',
  "you got a message from grandma would you like to hear what grandma has to say": 'b329',
  "here is grandma": 'b330',
  "would you like to send grandma a big hug back": 'b331',
  "whoosh your hug is flying to grandma": 'b332',
  "grandma would love a hug back shall we send one": 'b333',
  "grandma left you a special bedtime message": 'b334',
  "you got a message from grandad would you like to hear what grandad has to say": 'b335',
  "here is grandad": 'b336',
  "would you like to send grandad a big hug back": 'b337',
  "whoosh your hug is flying to grandad": 'b338',
  "grandad would love a hug back shall we send one": 'b339',
  "grandad left you a special bedtime message": 'b340',
  "you got a message from nana would you like to hear what nana has to say": 'b341',
  "here is nana": 'b342',
  "would you like to send nana a big hug back": 'b343',
  "whoosh your hug is flying to nana": 'b344',
  "nana would love a hug back shall we send one": 'b345',
  "nana left you a special bedtime message": 'b346',
  "you got a message from auntie would you like to hear what auntie has to say": 'b347',
  "here is auntie": 'b348',
  "would you like to send auntie a big hug back": 'b349',
  "whoosh your hug is flying to auntie": 'b350',
  "auntie would love a hug back shall we send one": 'b351',
  "auntie left you a special bedtime message": 'b352',
  "you got a message from uncle would you like to hear what uncle has to say": 'b353',
  "here is uncle": 'b354',
  "would you like to send uncle a big hug back": 'b355',
  "whoosh your hug is flying to uncle": 'b356',
  "uncle would love a hug back shall we send one": 'b357',
  "uncle left you a special bedtime message": 'b358',
  "okay i'll keep it safe in your letterbox": 'b359',
  "wasn't that lovely": 'b360',
  "maybe another time": 'b361',
  "psst": 'b362',
  "no letters yet when someone who loves you sends one i will bring it straight to you": 'b363',
  "you got a message": 'b364',
  "would you like to hear it": 'b365',
  "would you like to send a big hug back": 'b366',
  "whoosh your hug is on its way": 'b367',
  "yaaawn i'm getting sooo sleepy": 'b368',
  "before i sleep": 'b369',
  "night night": 'b370',
  "thank you for playing with me see you tomorrow": 'b371',
  "shhh i'm sleeping see you tomorrow": 'b372',
  "shhh i'm dreaming about you": 'b373',
  "i'm awake let's play a little more": 'b374',
  "woohoo": 'b375',
  "yay": 'b376',
  "hooray": 'b377',
  "you rock": 'b378',
  "high five": 'b379',
  "awesome": 'b380',
  "wow wow wow": 'b381',
  "yippee": 'b382',
  "so clever": 'b383',
  "oopsie try another one": 'b384',
  "hee hee not that one": 'b385',
  "nearly try again": 'b386',
  "try again": 'b387',
  "three in a row you're on fire": 'b388',
  "super streak": 'b389',
  "mmm": 'b390',
  "yum": 'b391',
  "crunchy": 'b392',
  "delicious": 'b393',
  "yummy in my tummy": 'b394',
  "buuurp oops excuse me": 'b395',
  "watch me eat count with me": 'b396',
  "how many did i eat": 'b397',
  "feed me": 'b398',
  "dance break tap me to make me dance": 'b399',
  "faster faster": 'b400',
  "wheee": 'b401',
  "phew that was fun let's keep going": 'b402',
  "psst over here": 'b403',
  "your turn tap one": 'b404',
  "come on you can do it": 'b405',
  "let's go": 'b406',
  "ready steady go": 'b407',
  "clap with me": 'b408',
  "clap clap clap": 'b409',
  "let's play": 'b410',
  "tap a game": 'b411',
  "pop": 'b412',
  "boing": 'b413',
  "ta da": 'b414',
  "look it's growing": 'b415',
  "big finish": 'b416',
  "hello poke me tickle me talk to me": 'b417',
  "talk to me i'll copy you": 'b418',
  "i'm listening": 'b419',
  "say something": 'b420',
  "ouch my head": 'b421',
  "hee hee hee that tickles": 'b422',
  "ahh i love hugs": 'b423',
  "yum yum": 'b424',
  "whee again again": 'b425',
  "don't poke my nose": 'b426',
  "la la la": 'b427',
  "what's this say it out loud": 'b428',
  "i heard you brilliant": 'b429',
  "let's say it together": 'b430',
  "louder i can't hear you": 'b431',
  "count out loud with me": 'b432',
  "tap the microphone and say it": 'b433',
  "say it": 'b434',
  "it's an apple": 'b435',
  "it's a banana": 'b436',
  "it's a cat": 'b437',
  "it's a dog": 'b438',
  "it's a fish": 'b439',
  "it's a lion": 'b440',
  "it's a monkey": 'b441',
  "it's a pig": 'b442',
  "it's a turtle": 'b443',
  "it's a zebra": 'b444',
  "it's a bear": 'b445',
  "it's a star": 'b446',
  "it's the sun": 'b447',
  "it's a cake": 'b448',
  "it's a balloon": 'b449',
  "it's a rainbow": 'b450',
  "it's an octopus": 'b451',
  "it's an egg": 'b452',
  "it's a hat": 'b453',
  "it's a heart": 'b454',
  "it's a strawberry": 'b455',
  "it's an orange": 'b456',
  "it's a cookie": 'b457',
  "it's a cupcake": 'b458',
  "it's a chick": 'b459',
  "it's a ladybird": 'b460',
  "it's a mushroom": 'b461',
  "it's a present": 'b462',
  "hey come and play with me": 'b463',
  "look a balloon pop it": 'b464',
  "ooh a present what's inside": 'b465',
  "dance with me": 'b466',
  "guess what a new friend is coming to visit": 'b467',
  "look who's here": 'b468',
  "say hello to my new friend": 'b469',
  "tap a game and let's play": 'b470',
  "wheee bubbles pop pop pop": 'b471',
  "let's have a party": 'b472',
  "can you find me": 'b473',
  "peekaboo": 'b474',
  "shake shake shake": 'b475',
  "knock knock it's me": 'b476',
  "i'm so happy you're here": 'b477',
  "hoo hoo i'm momo i love letters": 'f_momo_0',
  "hoo ray wonderful": 'f_momo_1',
  "twit twoo you're so clever": 'f_momo_2',
  "hee hee my glasses are wobbly": 'f_momo_3',
  "let's read together": 'f_momo_4',
  "hoo hoo try again": 'f_momo_5',
  "hi i'm tiko i build things stomp stomp": 'f_tiko_0',
  "roarrr some": 'f_tiko_1',
  "great building": 'f_tiko_2',
  "oops i dropped my hammer again": 'f_tiko_3',
  "stomp stomp hee hee": 'f_tiko_4',
  "uh oh wobbly try again": 'f_tiko_5',
  "hello i'm lulu let's party": 'f_lulu_0',
  "sparkle sparkle yay": 'f_lulu_1',
  "party party party": 'f_lulu_2',
  "hee hee that tickles my fluff": 'f_lulu_3',
  "wheee rainbows": 'f_lulu_4',
  "oopsie daisy try again": 'f_lulu_5',
  "ribbit i'm gogo let's make some noise": 'f_gogo_0',
  "ribbit ribbit hooray": 'f_gogo_1',
  "big frog high five": 'f_gogo_2',
  "blub blub bubble burp": 'f_gogo_3',
  "boing boing boing": 'f_gogo_4',
  "ribbit try again": 'f_gogo_5',
  "hi hi i'm pip i count everything": 'f_pip_0',
  "one two three hooray": 'f_pip_1',
  "hop hop yay": 'f_pip_2',
  "my ears are tickly": 'f_pip_3',
  "count with me": 'f_pip_4',
  "hop and try again": 'f_pip_5',
};
