// Generated from the recorded voice lines. Do not edit by hand.

/// Recorded voices (Bibi and friends): normalised line text to clip file in assets/voice.
const voiceClips = <String, String>{
  "zero": 'b000',
  "one": 'b001',
  "two": 'b002',
  "three": 'b003',
  "four": 'b004',
  "five": 'b005',
  "six": 'b006',
  "seven": 'b007',
  "eight": 'b008',
  "nine": 'b009',
  "ten": 'b010',
  "my tummy is rumbling": 'b011',
  "nom nom nom": 'b012',
  "whoa that's too many for my little tummy": 'b013',
  "hmm i'm still hungry i need a few more": 'b014',
  "my bowl is empty tap the fruit to fill it up": 'b015',
  "can you give me one apple please": 'b016',
  "can you give me one strawberry please": 'b017',
  "can you give me one banana please": 'b018',
  "can you give me one blueberry please": 'b019',
  "can you give me one cookie please": 'b020',
  "can you give me one orange please": 'b021',
  "can you give me two apples please": 'b022',
  "can you give me two strawberries please": 'b023',
  "can you give me two bananas please": 'b024',
  "can you give me two blueberries please": 'b025',
  "can you give me two cookies please": 'b026',
  "can you give me two oranges please": 'b027',
  "can you give me three apples please": 'b028',
  "can you give me three strawberries please": 'b029',
  "can you give me three bananas please": 'b030',
  "can you give me three blueberries please": 'b031',
  "can you give me three cookies please": 'b032',
  "can you give me three oranges please": 'b033',
  "can you give me four apples please": 'b034',
  "can you give me four strawberries please": 'b035',
  "can you give me four bananas please": 'b036',
  "can you give me four blueberries please": 'b037',
  "can you give me four cookies please": 'b038',
  "can you give me four oranges please": 'b039',
  "can you give me five apples please": 'b040',
  "can you give me five strawberries please": 'b041',
  "can you give me five bananas please": 'b042',
  "can you give me five blueberries please": 'b043',
  "can you give me five cookies please": 'b044',
  "can you give me five oranges please": 'b045',
  "can you give me six apples please": 'b046',
  "can you give me six strawberries please": 'b047',
  "can you give me six bananas please": 'b048',
  "can you give me six blueberries please": 'b049',
  "can you give me six cookies please": 'b050',
  "can you give me six oranges please": 'b051',
  "can you give me seven apples please": 'b052',
  "can you give me seven strawberries please": 'b053',
  "can you give me seven bananas please": 'b054',
  "can you give me seven blueberries please": 'b055',
  "can you give me seven cookies please": 'b056',
  "can you give me seven oranges please": 'b057',
  "can you give me eight apples please": 'b058',
  "can you give me eight strawberries please": 'b059',
  "can you give me eight bananas please": 'b060',
  "can you give me eight blueberries please": 'b061',
  "can you give me eight cookies please": 'b062',
  "can you give me eight oranges please": 'b063',
  "can you give me nine apples please": 'b064',
  "can you give me nine strawberries please": 'b065',
  "can you give me nine bananas please": 'b066',
  "can you give me nine blueberries please": 'b067',
  "can you give me nine cookies please": 'b068',
  "can you give me nine oranges please": 'b069',
  "can you give me ten apples please": 'b070',
  "can you give me ten strawberries please": 'b071',
  "can you give me ten bananas please": 'b072',
  "can you give me ten blueberries please": 'b073',
  "can you give me ten cookies please": 'b074',
  "can you give me ten oranges please": 'b075',
  "yes brilliant": 'b076',
  "you got it": 'b077',
  "woohoo well done": 'b078',
  "super clever": 'b079',
  "yay that's right": 'b080',
  "this is a it says ah": 'b081',
  "pop the bubble that starts with ah": 'b082',
  "ah ah ant": 'b083',
  "that's an ant": 'b084',
  "i think it starts with a am i right": 'b085',
  "it starts with a": 'b086',
  "this is b it says buh": 'b087',
  "pop the bubble that starts with buh": 'b088',
  "buh buh bear": 'b089',
  "that's a bear": 'b090',
  "i think it starts with b am i right": 'b091',
  "it starts with b": 'b092',
  "this is c it says kuh": 'b093',
  "pop the bubble that starts with kuh": 'b094',
  "kuh kuh cat": 'b095',
  "that's a cat": 'b096',
  "i think it starts with c am i right": 'b097',
  "it starts with c": 'b098',
  "this is d it says duh": 'b099',
  "pop the bubble that starts with duh": 'b100',
  "duh duh dog": 'b101',
  "that's a dog": 'b102',
  "i think it starts with d am i right": 'b103',
  "it starts with d": 'b104',
  "this is e it says eh": 'b105',
  "pop the bubble that starts with eh": 'b106',
  "eh eh egg": 'b107',
  "that's an egg": 'b108',
  "i think it starts with e am i right": 'b109',
  "it starts with e": 'b110',
  "this is f it says ffff": 'b111',
  "pop the bubble that starts with ffff": 'b112',
  "ffff ffff fish": 'b113',
  "that's a fish": 'b114',
  "i think it starts with f am i right": 'b115',
  "it starts with f": 'b116',
  "this is g it says guh": 'b117',
  "pop the bubble that starts with guh": 'b118',
  "guh guh gorilla": 'b119',
  "that's a gorilla": 'b120',
  "i think it starts with g am i right": 'b121',
  "it starts with g": 'b122',
  "this is h it says huh": 'b123',
  "pop the bubble that starts with huh": 'b124',
  "huh huh hat": 'b125',
  "that's a hat": 'b126',
  "i think it starts with h am i right": 'b127',
  "it starts with h": 'b128',
  "this is l it says llll": 'b129',
  "pop the bubble that starts with llll": 'b130',
  "llll llll lion": 'b131',
  "that's a lion": 'b132',
  "i think it starts with l am i right": 'b133',
  "it starts with l": 'b134',
  "this is m it says mmmm": 'b135',
  "pop the bubble that starts with mmmm": 'b136',
  "mmmm mmmm monkey": 'b137',
  "that's a monkey": 'b138',
  "i think it starts with m am i right": 'b139',
  "it starts with m": 'b140',
  "this is n it says nnnn": 'b141',
  "pop the bubble that starts with nnnn": 'b142',
  "nnnn nnnn nest": 'b143',
  "that's a nest": 'b144',
  "i think it starts with n am i right": 'b145',
  "it starts with n": 'b146',
  "this is o it says oh": 'b147',
  "pop the bubble that starts with oh": 'b148',
  "oh oh octopus": 'b149',
  "that's an octopus": 'b150',
  "i think it starts with o am i right": 'b151',
  "it starts with o": 'b152',
  "this is p it says puh": 'b153',
  "pop the bubble that starts with puh": 'b154',
  "puh puh pig": 'b155',
  "that's a pig": 'b156',
  "i think it starts with p am i right": 'b157',
  "it starts with p": 'b158',
  "this is r it says rrrr": 'b159',
  "pop the bubble that starts with rrrr": 'b160',
  "rrrr rrrr rainbow": 'b161',
  "that's a rainbow": 'b162',
  "i think it starts with r am i right": 'b163',
  "it starts with r": 'b164',
  "this is s it says ssss": 'b165',
  "pop the bubble that starts with ssss": 'b166',
  "ssss ssss sun": 'b167',
  "that's the sun": 'b168',
  "i think it starts with s am i right": 'b169',
  "it starts with s": 'b170',
  "this is t it says tuh": 'b171',
  "pop the bubble that starts with tuh": 'b172',
  "tuh tuh turtle": 'b173',
  "that's a turtle": 'b174',
  "i think it starts with t am i right": 'b175',
  "it starts with t": 'b176',
  "this is z it says zzzz": 'b177',
  "pop the bubble that starts with zzzz": 'b178',
  "zzzz zzzz zebra": 'b179',
  "that's a zebra": 'b180',
  "i think it starts with z am i right": 'b181',
  "it starts with z": 'b182',
  "let's build a house": 'b183',
  "look we built a whole house together": 'b184',
  "find the square for the walls": 'b185',
  "now find the triangle for the roof": 'b186',
  "now find the rectangle for the door": 'b187',
  "now find the circle for the sun": 'b188',
  "now find the star for the sky": 'b189',
  "a square": 'b190',
  "that's a square": 'b191',
  "can you find the square": 'b192',
  "a triangle": 'b193',
  "that's a triangle": 'b194',
  "can you find the triangle": 'b195',
  "a rectangle": 'b196',
  "that's a rectangle": 'b197',
  "can you find the rectangle": 'b198',
  "a circle": 'b199',
  "that's a circle": 'b200',
  "can you find the circle": 'b201',
  "a star": 'b202',
  "that's a star": 'b203',
  "can you find the star": 'b204',
  "a heart": 'b205',
  "that's a heart": 'b206',
  "can you find the heart": 'b207',
  "a diamond": 'b208',
  "that's a diamond": 'b209',
  "can you find the diamond": 'b210',
  "an oval": 'b211',
  "that's an oval": 'b212',
  "can you find the oval": 'b213',
  "balloon": 'b214',
  "cake": 'b215',
  "present": 'b216',
  "star": 'b217',
  "strawberry": 'b218',
  "cupcake": 'b219',
  "popper": 'b220',
  "lolly": 'b221',
  "party time": 'b222',
  "what comes next": 'b223',
  "let's party": 'b224',
  "hmm let's sing the pattern together": 'b225',
  "i'm learning to count let me try": 'b226',
  "let me count these": 'b227',
  "yippee i got one right thank you for checking teacher": 'b228',
  "hmm i think i was counting my toes": 'b229',
  "oopsie my brain did a wobble": 'b230',
  "silly me my leaf was in my eyes": 'b231',
  "oh no i was thinking about cake again": 'b232',
  "can you teach me how many are there really": 'b233',
  "can you teach me which letter does it start with": 'b234',
  "hmm let's count together": 'b235',
  "ohhh now i know you are the best teacher": 'b236',
  "hmm shall we count them together tap each one": 'b237',
  "listen carefully and try again": 'b238',
  "i think there is one am i right": 'b239',
  "there is one": 'b240',
  "i think there are two am i right": 'b241',
  "there are two": 'b242',
  "i think there are three am i right": 'b243',
  "there are three": 'b244',
  "i think there are four am i right": 'b245',
  "there are four": 'b246',
  "i think there are five am i right": 'b247',
  "there are five": 'b248',
  "i think there are six am i right": 'b249',
  "there are six": 'b250',
  "i think there are seven am i right": 'b251',
  "there are seven": 'b252',
  "i think there are eight am i right": 'b253',
  "there are eight": 'b254',
  "i think there are nine am i right": 'b255',
  "there are nine": 'b256',
  "i think there are ten am i right": 'b257',
  "there are ten": 'b258',
  "good morning": 'b259',
  "hello": 'b260',
  "good evening": 'b261',
  "i missed you": 'b262',
  "what shall we do next": 'b263',
  "i had a dream about you": 'b264',
  "we were flying on a giant banana": 'b265',
  "we had a picnic on the moon and the cheese was yummy": 'b266',
  "you and me were swimming with a friendly whale": 'b267',
  "we built a castle out of jelly and it wobbled": 'b268',
  "we found a rainbow slide and went whoosh": 'b269',
  "how are you feeling today": 'b270',
  "yay happy is my favourite let's have fun": 'b271',
  "aww here's a big squishy hug i'm right here with you": 'b272',
  "me too a little bit let's take it nice and slow": 'b273',
  "that's okay let's take a big dragon breath together in and out better": 'b274',
  "hee hee that tickles": 'b275',
  "boop you booped me": 'b276',
  "i love playing with you": 'b277',
  "did you know i grow when you learn": 'b278',
  "my leaf is doing a happy dance": 'b279',
  "let's learn something amazing": 'b280',
  "look at my stars that's from all our counting": 'b281',
  "i love my book hat letters make me so clever": 'b282',
  "look at my flower i'm a superstar now": 'b283',
  "surprise i found a shiny star in my leaf it's for you": 'b284',
  "feeding time": 'b285',
  "letter garden": 'b286',
  "shape builder": 'b287',
  "pattern party": 'b288',
  "teach me": 'b289',
  "your sticker album": 'b290',
  "your letterbox": 'b291',
  "your letterbox something is waiting inside": 'b292',
  "wow i just grew bigger thank you for teaching me": 'b293',
  "you did it you are a superstar": 'b294',
  "wow my brain feels so much bigger now": 'b295',
  "hooray you are the best teacher in the whole world": 'b296',
  "amazing i'm growing because of you": 'b297',
  "and look a new sticker for your album": 'b298',
  "play a game to win your very first sticker": 'b299',
  "wow look at all your stickers": 'b300',
  "ooh shiny": 'b301',
  "i love that one": 'b302',
  "so cool": 'b303',
  "wiggle wiggle": 'b304',
  "look a magic egg tap it to wake it up": 'b305',
  "ooh it moved": 'b306',
  "keep going": 'b307',
  "i can hear something inside": 'b308',
  "one more big tap": 'b309',
  "hello i'm your very own creature what should my name be": 'b310',
  "bibi i love it i'm bibi": 'b311',
  "pip i love it i'm pip": 'b312',
  "mochi i love it i'm mochi": 'b313',
  "sunny i love it i'm sunny": 'b314',
  "bean i love it i'm bean": 'b315',
  "coco i love it i'm coco": 'b316',
  "you got a message from mummy would you like to hear what mummy has to say": 'b317',
  "here is mummy": 'b318',
  "would you like to send mummy a big hug back": 'b319',
  "whoosh your hug is flying to mummy": 'b320',
  "mummy would love a hug back shall we send one": 'b321',
  "mummy left you a special bedtime message": 'b322',
  "you got a message from daddy would you like to hear what daddy has to say": 'b323',
  "here is daddy": 'b324',
  "would you like to send daddy a big hug back": 'b325',
  "whoosh your hug is flying to daddy": 'b326',
  "daddy would love a hug back shall we send one": 'b327',
  "daddy left you a special bedtime message": 'b328',
  "you got a message from grandma would you like to hear what grandma has to say": 'b329',
  "here is grandma": 'b330',
  "would you like to send grandma a big hug back": 'b331',
  "whoosh your hug is flying to grandma": 'b332',
  "grandma would love a hug back shall we send one": 'b333',
  "grandma left you a special bedtime message": 'b334',
  "you got a message from grandad would you like to hear what grandad has to say": 'b335',
  "here is grandad": 'b336',
  "would you like to send grandad a big hug back": 'b337',
  "whoosh your hug is flying to grandad": 'b338',
  "grandad would love a hug back shall we send one": 'b339',
  "grandad left you a special bedtime message": 'b340',
  "you got a message from nana would you like to hear what nana has to say": 'b341',
  "here is nana": 'b342',
  "would you like to send nana a big hug back": 'b343',
  "whoosh your hug is flying to nana": 'b344',
  "nana would love a hug back shall we send one": 'b345',
  "nana left you a special bedtime message": 'b346',
  "you got a message from auntie would you like to hear what auntie has to say": 'b347',
  "here is auntie": 'b348',
  "would you like to send auntie a big hug back": 'b349',
  "whoosh your hug is flying to auntie": 'b350',
  "auntie would love a hug back shall we send one": 'b351',
  "auntie left you a special bedtime message": 'b352',
  "you got a message from uncle would you like to hear what uncle has to say": 'b353',
  "here is uncle": 'b354',
  "would you like to send uncle a big hug back": 'b355',
  "whoosh your hug is flying to uncle": 'b356',
  "uncle would love a hug back shall we send one": 'b357',
  "uncle left you a special bedtime message": 'b358',
  "okay i'll keep it safe in your letterbox": 'b359',
  "wasn't that lovely": 'b360',
  "maybe another time": 'b361',
  "psst": 'b362',
  "no letters yet when someone who loves you sends one i will bring it straight to you": 'b363',
  "you got a message": 'b364',
  "would you like to hear it": 'b365',
  "would you like to send a big hug back": 'b366',
  "whoosh your hug is on its way": 'b367',
  "yaaawn i'm getting sooo sleepy": 'b368',
  "before i sleep": 'b369',
  "night night": 'b370',
  "thank you for playing with me see you tomorrow": 'b371',
  "shhh i'm sleeping see you tomorrow": 'b372',
  "shhh i'm dreaming about you": 'b373',
  "i'm awake let's play a little more": 'b374',
  "woohoo": 'b375',
  "yay": 'b376',
  "hooray": 'b377',
  "you rock": 'b378',
  "high five": 'b379',
  "awesome": 'b380',
  "wow wow wow": 'b381',
  "yippee": 'b382',
  "so clever": 'b383',
  "oopsie try another one": 'b384',
  "hee hee not that one": 'b385',
  "nearly try again": 'b386',
  "try again": 'b387',
  "three in a row you're on fire": 'b388',
  "super streak": 'b389',
  "mmm": 'b390',
  "yum": 'b391',
  "crunchy": 'b392',
  "delicious": 'b393',
  "yummy in my tummy": 'b394',
  "buuurp oops excuse me": 'b395',
  "watch me eat count with me": 'b396',
  "how many did i eat": 'b397',
  "feed me": 'b398',
  "dance break tap me to make me dance": 'b399',
  "faster faster": 'b400',
  "wheee": 'b401',
  "phew that was fun let's keep going": 'b402',
  "psst over here": 'b403',
  "your turn tap one": 'b404',
  "come on you can do it": 'b405',
  "let's go": 'b406',
  "ready steady go": 'b407',
  "clap with me": 'b408',
  "clap clap clap": 'b409',
  "let's play": 'b410',
  "tap a game": 'b411',
  "pop": 'b412',
  "boing": 'b413',
  "ta da": 'b414',
  "look it's growing": 'b415',
  "big finish": 'b416',
  "hello poke me tickle me talk to me": 'b417',
  "talk to me i'll copy you": 'b418',
  "i'm listening": 'b419',
  "say something": 'b420',
  "ouch my head": 'b421',
  "hee hee hee that tickles": 'b422',
  "ahh i love hugs": 'b423',
  "yum yum": 'b424',
  "whee again again": 'b425',
  "don't poke my nose": 'b426',
  "la la la": 'b427',
  "what's this say it out loud": 'b428',
  "i heard you brilliant": 'b429',
  "let's say it together": 'b430',
  "louder i can't hear you": 'b431',
  "count out loud with me": 'b432',
  "tap the microphone and say it": 'b433',
  "say it": 'b434',
  "it's an apple": 'b435',
  "it's a banana": 'b436',
  "it's a cat": 'b437',
  "it's a dog": 'b438',
  "it's a fish": 'b439',
  "it's a lion": 'b440',
  "it's a monkey": 'b441',
  "it's a pig": 'b442',
  "it's a turtle": 'b443',
  "it's a zebra": 'b444',
  "it's a bear": 'b445',
  "it's a star": 'b446',
  "it's the sun": 'b447',
  "it's a cake": 'b448',
  "it's a balloon": 'b449',
  "it's a rainbow": 'b450',
  "it's an octopus": 'b451',
  "it's an egg": 'b452',
  "it's a hat": 'b453',
  "it's a heart": 'b454',
  "it's a strawberry": 'b455',
  "it's an orange": 'b456',
  "it's a cookie": 'b457',
  "it's a cupcake": 'b458',
  "it's a chick": 'b459',
  "it's a ladybird": 'b460',
  "it's a mushroom": 'b461',
  "it's a present": 'b462',
  "hey come and play with me": 'b463',
  "look a balloon pop it": 'b464',
  "ooh a present what's inside": 'b465',
  "dance with me": 'b466',
  "guess what a new friend is coming to visit": 'b467',
  "look who's here": 'b468',
  "say hello to my new friend": 'b469',
  "tap a game and let's play": 'b470',
  "wheee bubbles pop pop pop": 'b471',
  "let's have a party": 'b472',
  "can you find me": 'b473',
  "peekaboo": 'b474',
  "shake shake shake": 'b475',
  "knock knock it's me": 'b476',
  "i'm so happy you're here": 'b477',
  "level one": 'b478',
  "level two": 'b479',
  "level three": 'b480',
  "level four": 'b481',
  "super level": 'b482',
  "hooray you unlocked a new level": 'b483',
  "next time something new is waiting": 'b484',
  "let's look at my plates": 'b485',
  "which plate has more": 'b486',
  "which plate has fewer": 'b487',
  "yes that plate has more": 'b488',
  "yes that plate has fewer": 'b489',
  "hmm count them both try again": 'b490',
  "one more one more": 'b491',
  "count the fruit on my plate": 'b492',
  "now give me one more": 'b493',
  "now give me two more": 'b494',
  "how many now": 'b495',
  "snack time watch my plate": 'b496',
  "now i'll eat some munch munch": 'b497',
  "how many are left": 'b498',
  "letter hunt": 'b499',
  "big letters and little letters": 'b500',
  "find the little letter that matches": 'b501',
  "let's spell words": 'b502',
  "tap the letters in order": 'b503',
  "which sound comes next": 'b504',
  "you spelled it": 'b505',
  "pop the letter a": 'b506',
  "pop the letter b": 'b507',
  "pop the letter c": 'b508',
  "pop the letter d": 'b509',
  "pop the letter e": 'b510',
  "pop the letter f": 'b511',
  "pop the letter g": 'b512',
  "pop the letter h": 'b513',
  "pop the letter l": 'b514',
  "pop the letter m": 'b515',
  "pop the letter n": 'b516',
  "pop the letter o": 'b517',
  "pop the letter p": 'b518',
  "pop the letter r": 'b519',
  "pop the letter s": 'b520',
  "pop the letter t": 'b521',
  "pop the letter z": 'b522',
  "let's spell cat": 'b523',
  "kuh ah tuh cat": 'b524',
  "let's spell dog": 'b525',
  "duh oh guh dog": 'b526',
  "let's spell hat": 'b527',
  "huh ah tuh hat": 'b528',
  "let's spell pig": 'b529',
  "puh ih guh pig": 'b530',
  "let's spell sun": 'b531',
  "ssss uh nnnn sun": 'b532',
  "let's spell ant": 'b533',
  "ah nnnn tuh ant": 'b534',
  "let's spell egg": 'b535',
  "eh guh guh egg": 'b536',
  "ah": 'b537',
  "duh": 'b538',
  "eh": 'b539',
  "guh": 'b540',
  "huh": 'b541',
  "ih": 'b542',
  "kuh": 'b543',
  "nnnn": 'b544',
  "oh": 'b545',
  "puh": 'b546',
  "ssss": 'b547',
  "tuh": 'b548',
  "uh": 'b549',
  "let's build a rocket": 'f_tiko_9',
  "find the rectangle for the rocket": 'b551',
  "now find the triangle for the nose": 'b552',
  "now find the circle for the window": 'b553',
  "now find the diamond for the fire": 'b554',
  "look we built a rocket three two one blast off": 'b555',
  "let's build a boat": 'b556',
  "find the oval for the boat": 'b557',
  "now find the triangle for the sail": 'b558',
  "now find the rectangle for the mast": 'b559',
  "now find the heart for the flag": 'b560',
  "look we built a boat splish splash": 'b561',
  "let's build a robot": 'b562',
  "find the square for the robot's head": 'b563',
  "now find the rectangle for the body": 'b564',
  "now find the circle for the eyes": 'b565',
  "now find the heart for the robot's heart": 'b566',
  "now find the star for the antenna": 'b567',
  "look we built a robot beep boop": 'b568',
  "trickier patterns": 'b569',
  "oh no something is missing": 'b570',
  "what's missing": 'b571',
  "counting patterns": 'b572',
  "count the stars what comes next": 'b573',
  "i'm learning shapes let me try": 'b574',
  "big numbers are tricky let me try": 'b575',
  "which shape is it really": 'b576',
  "i think this is a square am i right": 'b577',
  "i think this is a triangle am i right": 'b578',
  "i think this is a rectangle am i right": 'b579',
  "i think this is a circle am i right": 'b580',
  "i think this is a star am i right": 'b581',
  "i think this is a heart am i right": 'b582',
  "i think this is a diamond am i right": 'b583',
  "i think this is an oval am i right": 'b584',
  "let's try one more time": 'b585',
  "this is how you say it": 'b586',
  "now you say it": 'b587',
  "hee hee do i have to teach you everything": 'b588',
  "take your time i'm listening": 'b589',
  "let's make sentences": 'b590',
  "now make a sentence with it": 'b591',
  "like this": 'b592',
  "wow what a great sentence": 'b593',
  "say a whole sentence with the word in it": 'b594',
  "say it with me": 'b595',
  "animal sounds and colours": 'b596',
  "opposites big and small": 'b597',
  "i like to eat apples": 'b598',
  "monkeys love bananas": 'b599',
  "the cat says meow": 'b600',
  "my dog can run fast": 'b601',
  "the fish can swim": 'b602',
  "the sun is hot": 'b603',
  "i love birthday cake": 'b604',
  "my balloon is red": 'b605',
  "i see a star in the sky": 'b606',
  "the bear is big and fluffy": 'b607',
  "the chick came out of the egg": 'b608',
  "i wear a hat on my head": 'b609',
  "what sound does a dog make": 'b610',
  "woof woof": 'b611',
  "what sound does a cat make": 'b612',
  "meow": 'b613',
  "what sound does a pig make": 'b614',
  "oink oink": 'b615',
  "what sound does a lion make": 'b616',
  "roar": 'b617',
  "what sound does a monkey make": 'b618',
  "ooh ooh aah aah": 'b619',
  "what sound does a chick make": 'b620',
  "cheep cheep": 'b621',
  "what colour is a banana": 'b622',
  "yellow": 'b623',
  "what colour is a strawberry": 'b624',
  "red": 'b625',
  "what colour is the sun": 'b626',
  "what colour is an orange": 'b627',
  "orange": 'b628',
  "what is the opposite of big": 'b629',
  "small": 'b630',
  "what is the opposite of hot": 'b631',
  "cold": 'b632',
  "what is the opposite of up": 'b633',
  "down": 'b634',
  "what is the opposite of day": 'b635',
  "night": 'b636',
  "what is the opposite of happy": 'b637',
  "sad": 'b638',
  "what is the opposite of fast": 'b639',
  "slow": 'b640',
  "what is the opposite of wet": 'b641',
  "dry": 'b642',
  "what is the opposite of open": 'b643',
  "closed": 'b644',
  "what is the opposite of tall": 'b645',
  "short": 'b646',
  "what is the opposite of loud": 'b647',
  "quiet": 'b648',
  "oh maybe i got you wrong can you say it again": 'b649',
  "hmm i heard something different": 'b650',
  "say it slowly and loudly": 'b651',
  "can you spell it": 'b652',
  "let's spell it together": 'b653',
  "spell it with me": 'b654',
  "you spelled it amazing": 'b655',
  "wow you said it perfectly": 'b656',
  "listen carefully": 'b657',
  "sing and dance with me": 'b658',
  "let's sing a song": 'b659',
  "pick a song": 'b660',
  "everybody dance": 'b661',
  "that was so much fun again": 'b662',
  "come on friends let's dance": 'b663',
  "clap along with me": 'b664',
  "a": 'b665',
  "b": 'b666',
  "c": 'b667',
  "d": 'b668',
  "e": 'b669',
  "f": 'b670',
  "g": 'b671',
  "h": 'b672',
  "i": 'b673',
  "j": 'b674',
  "k": 'b675',
  "l": 'b676',
  "m": 'b677',
  "n": 'b678',
  "o": 'b679',
  "p": 'b680',
  "q": 'b681',
  "r": 'b682',
  "s": 'b683',
  "t": 'b684',
  "u": 'b685',
  "v": 'b686',
  "w": 'b687',
  "x": 'b688',
  "y": 'b689',
  "z": 'b690',
  "hello are you there say something": 'b691',
  "i'm all ears say hello to me": 'b692',
  "psst i'm waiting for your lovely voice": 'b693',
  "talk to me i love your voice": 'b694',
  "hmm it's very quiet can you say it louder": 'b695',
  "why did the banana go to the doctor because it wasn't peeling well hee hee": 'b696',
  "what do you call a sleeping dinosaur a dino snore": 'b697',
  "what do you call a bear with no teeth a gummy bear hee hee": 'b698',
  "why are fish so clever because they live in schools": 'b699',
  "what did one plate say to the other lunch is on me": 'b700',
  "did you say that": 'b701',
  "hi what's your name": 'b702',
  "what a lovely name": 'b703',
  "nice to meet you": 'b704',
  "i knew it i remember you": 'b705',
  "tap the letters to spell it": 'b706',
  "say it again nice and loud": 'b707',
  "i heard you say something else": 'b708',
  "you sound amazing": 'b709',
  "hee hee you sound funny": 'b710',
  "say it with me ready": 'b711',
  "plus": 'b712',
  "makes": 'b713',
  "how many altogether": 'b714',
  "let's add them up": 'b715',
  "sum time": 'b716',
  "count them all together": 'b717',
  "take away": 'b718',
  "everybody dance with us": 'b719',
  "dance with me and my friends": 'b720',
  "wave your arms": 'b721',
  "jump up high": 'b722',
  "spin around": 'b723',
  "you are a super dancer": 'b724',
  "pick a song and let's dance": 'b725',
  "sing along with us": 'b726',
  "shall we sing another one": 'b727',
  "what a lovely dancer you are": 'b728',
  "hello friends": 'b729',
  "the apple song": 'b730',
  "count and jump": 'b731',
  "the letter song": 'b732',
  "shape dance": 'b733',
  "rainbow song": 'b734',
  "farm party": 'b735',
  "wiggle disco": 'b736',
  "happy clap": 'b737',
  "goodnight song": 'b738',
  "songs": 'b739',
  "sing": 'b740',
  "level five": 'b741',
  "level six": 'b742',
  "level seven": 'b743',
  "shall we sing it again": 'b744',
  "let's sing it again": 'b745',
  "okay let's pick another song": 'b746',
  "let's build a castle": 'b747',
  "find the square for the castle wall": 'b748',
  "now find the rectangle for the tower": 'b749',
  "now find the triangle for the tower roof": 'b750',
  "look we built a castle fit for a king and queen": 'b751',
  "let's build a train": 'b752',
  "find the rectangle for the train": 'b753',
  "now find the square for the cabin": 'b754',
  "now find the circle for the wheels": 'b755',
  "now find the diamond for the lamp": 'b756',
  "look we built a train choo choo": 'b757',
  "let's build a flower": 'b758',
  "find the circle for the middle of the flower": 'b759',
  "now find the heart for the petals": 'b760',
  "now find the rectangle for the stem": 'b761',
  "now find the oval for the leaf": 'b762',
  "look we built a beautiful flower": 'b763',
  "counting in twos": 'b764',
  "count in twos what comes next": 'b765',
  "i'm learning sums let me try": 'b766',
  "i think": 'b767',
  "am i right": 'b768',
  "how many does it really make": 'b769',
  "rhyme time": 'b770',
  "yes they rhyme": 'b771',
  "how many can you see say it out loud": 'b772',
  "what rhymes with cat": 'b773',
  "cat and hat they rhyme": 'b774',
  "what rhymes with dog": 'b775',
  "dog and log they rhyme": 'b776',
  "what rhymes with sun": 'b777',
  "sun and fun they rhyme": 'b778',
  "what rhymes with pig": 'b779',
  "pig and wig they rhyme": 'b780',
  "what rhymes with hat": 'b781',
  "hat and cat they rhyme": 'b782',
  "what rhymes with star": 'b783',
  "star and car they rhyme": 'b784',
  "what rhymes with bear": 'b785',
  "bear and chair they rhyme": 'b786',
  "what rhymes with fish": 'b787',
  "fish and dish they rhyme": 'b788',
  "brainlings dance party": 'b789',
  "counting rocket": 'b790',
  "abc animal jam": 'b791',
  "bonus time catch the falling stars": 'b792',
  "wow you caught so many stars": 'b793',
  "minus": 'b794',
  "take away means some go away": 'b795',
  "this sign means take away we can also call it minus": 'b796',
  "again": 'b797',
  "one more time": 'b798',
  "let's go again": 'b799',
  "nearly let me help you": 'b800',
  "the answer is": 'b801',
  "let's spell it": 'b802',
  "your turn say it once": 'b803',
  "good try let's keep going": 'b804',
  "nearly here is a sentence": 'b805',
  "that's okay mistakes help us learn": 'b806',
  "good thinking let me show you": 'b807',
  "ooh so close let me help": 'b808',
  "you tried so hard i'm proud of you": 'b809',
  "you're so brilliant for trying": 'b810',
  "thank you for trying you're amazing": 'b811',
  "what a clever try": 'b812',
  "you're a star": 'b813',
  "i'm so proud of you": 'b814',
  "you're so smart": 'b815',
  "fantastic": 'b816',
  "not that one let's look again together": 'b817',
  "ooh nearly have another look": 'b818',
  "let's learn it together": 'b819',
  "hoo hoo i'm momo i love letters": 'f_momo_0',
  "hoo ray wonderful": 'f_momo_1',
  "twit twoo you're so clever": 'f_momo_2',
  "hee hee my glasses are wobbly": 'f_momo_3',
  "let's read together": 'f_momo_4',
  "hoo hoo try again": 'f_momo_5',
  "hi i'm tiko i build things stomp stomp": 'f_tiko_0',
  "roarrr some": 'f_tiko_1',
  "great building": 'f_tiko_2',
  "oops i dropped my hammer again": 'f_tiko_3',
  "stomp stomp hee hee": 'f_tiko_4',
  "uh oh wobbly try again": 'f_tiko_5',
  "hello i'm lulu let's party": 'f_lulu_0',
  "sparkle sparkle yay": 'f_lulu_1',
  "party party party": 'f_lulu_2',
  "hee hee that tickles my fluff": 'f_lulu_3',
  "wheee rainbows": 'f_lulu_4',
  "oopsie daisy try again": 'f_lulu_5',
  "ribbit i'm gogo let's make some noise": 'f_gogo_0',
  "ribbit ribbit hooray": 'f_gogo_1',
  "big frog high five": 'f_gogo_2',
  "blub blub bubble burp": 'f_gogo_3',
  "boing boing boing": 'f_gogo_4',
  "ribbit try again": 'f_gogo_5',
  "hi hi i'm pip i count everything": 'f_pip_0',
  "one two three hooray": 'f_pip_1',
  "hop hop yay": 'f_pip_2',
  "my ears are tickly": 'f_pip_3',
  "count with me": 'f_pip_4',
  "hop and try again": 'f_pip_5',
  "boing i'm a bouncy bunny": 'f_pip_6',
  "i counted all the carrots ten": 'f_pip_7',
  "let's hop together": 'f_pip_8',
  "wiggle your nose like me": 'f_pip_9',
  "carrots make me super fast": 'f_pip_10',
  "can you count to five one two three four five": 'f_pip_11',
  "books are my favourite thing": 'f_momo_6',
  "a is for amazing": 'f_momo_7',
  "who who you you": 'f_momo_8',
  "i read a story about a dragon": 'f_momo_9',
  "let's sing the alphabet": 'f_momo_10',
  "my feathers are so fluffy": 'f_momo_11',
  "i built a tower taller than me": 'f_tiko_6',
  "crash oops my tower fell": 'f_tiko_7',
  "big feet big stomps": 'f_tiko_8',
  "i love squares and triangles": 'f_tiko_10',
  "rawr that's my happy roar": 'f_tiko_11',
  "twirl and spin with me": 'f_lulu_6',
  "i love glitter and sparkles": 'f_lulu_7',
  "let's have a disco": 'f_lulu_8',
  "clap your hands clap clap": 'f_lulu_9',
  "rainbows are my favourite colour": 'f_lulu_10',
  "party hats for everyone": 'f_lulu_11',
  "jump like a frog boing": 'f_gogo_6',
  "i can catch flies with my tongue": 'f_gogo_7',
  "splish splash i love puddles": 'f_gogo_8',
  "say it loud ribbit": 'f_gogo_9',
  "croak croak that means hello": 'f_gogo_10',
  "let's sing a silly song": 'f_gogo_11',
};
